### ISSUE TITLE
C# 7.2 `in ValueType` parameters are not supported with .NET Standard / Core

### ISSUE THREAD

**Issue by stakx** [moq/moq4#605]
See this discussion over at DynamicProxy's repo: https://github.com/castleproject/Core/issues/339#issuecomment-372705522.

What needs to be done to add C# 7.2 reference semantics support in Moq for value types is this:

* [x] Upgrade Castle.Core package dependency to vNext once it's available (see https://github.com/castleproject/Core/issues/354).
* [X] ~~Add .NET Standard 2.0 as a target framework.~~ Not required, see below.
* [X] ~~Possibly update delegate generator logic, as per https://github.com/moq/moq4/issues/605#issuecomment-373309955.~~ Not required, see below.
* [X] Check whether `DynamicInvoke` e.g. for `Callback` and `Returns` is already lenient enough given differences in delegate signatures (presence of `in` parameter modifier), as per https://github.com/moq/moq4/issues/605#issuecomment-373343104

**Comment by zvirja** [comment]
BTW, just noticed that probably you and NSubstitute should also update our [delegate generators](https://github.com/moq/moq4/blob/d4aea9c344330b35487a2780736b04167e5ecb4a/Source/ProxyFactories/CastleProxyFactory.cs#L126). We don't copy the required modifiers as well, so in theory if you have delegate with `in ValueType`, it will fail.

**Comment by stakx** [comment]
@zvirja - Thanks a lot for that hint! True, this needs to be tested as well.

Another thing that comes to mind (which may or may not be relevant to NSubstitute) is that Moq does a lot of `DynamicInvoke`-ing on delegates, e.g. when you configure a `Callback` or `Returns` callback for a method call setup. Not sure at this point whether `DynamicInvoke` is flexible enough to glance over small differences in the delegate signatures, i.e. when the method being set up has an `in` parameter but the configured callback doesn't have the `in` modifier on the parameter. Will need to be tested, too.

Adding these two points to the list above.

**Comment by stakx** [comment]
**Add .NET Standard 2.0 as a target framework.** As it turns out, it appears that Moq doesn't need to add an additional TFM. The upgrade of Castle.Core to version 4.3.0 should be enough. If user code targets a platform that supports .NET Standard 1.5 (or newer), then the .NET Standard 1.5 version of Castle.Core will be selected even though Moq (which sits between Castle.Core and the targeted platform) only has a .NET Standard 1.3 assembly.

**Possibly update delegate generator logic.** Added some tests to verify delegate mocking works in the presence of `in` parameters. It seems for once, System.Reflection.Emit just does what it's supposed to.

**Check whether DynamicInvoke e.g. for Callback and Returns is already lenient enough given differences in delegate signatures.** Ran some quick successful tests; given that `DynamicInvoke` already worked with differences in `ref` / no-`ref`, perhaps it's not too surprising that `in` appears to be supported just fine, too.
