### ISSUE TITLE
Improve processing of multi-dot (also called "fluent" or "recursive") setup expressions

### ISSUE THREAD

**Issue by stakx** [moq/moq4#643]
This is a meta-issue that essentially covers the following previous issues:

* [x] #110 - Recursive property setup overrides previous setups
* [x] #142 - Recursive mocks don't work with argument matching 
* [x] #147 - Bug: Mocks of factories with parameters behave as if you use "It.IsAny(x)" if you mock a function call in the returned object.
* [x] #426 - mock.Setup(m => m.A.B.X) should setup only what's minimally required. It shouldn't setup all properties, nor override preexisting setups in A or B.
* [x] #556 - ~~Recursive setup expression creates ghost setups that make `VerifyAll` fail~~ (fixed by #684)

(I will close all of the above issues in favor of this one here.)

All of these are caused by the way Moq processes multi-dot setup expressions: It compiles the expression and executes them with `MockBehavior.Mock` temporarily enabled to create the whole object graph leading to the right-most object. Compilation means that matchers such as `It.IsAny` get "erased". Additionally, in order for `MockBehavior.Mock` to work, `SetupAllProperties` is executed at every step in the chain, which can cause previous setups to be "forgotten".

Instead of brute-forcing our way to the right-most object using the above approach, it would be better to actually split multi-dot expressions, let each mock handle a segment, and pass the remaining subexpression on to an "inner" mock. This would mean no compilation (making setup both faster and preserving matchers), and less overridden / forgotten setups, too.

Getting the multi-dot setup expression parsing to work is fairly easy, however replacing the current implementation in a way that doesn't introduce breaking changes is hard. What's additionally needed is a thorough set of regression tests that thoroughly cover the current behavior.

**Comment by stakx** [comment]
All done!
